name: Container image

inputs:
  push:
    required: false
    type: boolean
    default: false
  image:
    required: true
    type: string
  tags:
    required: false
    type: string
  build-args:
    required: false
    type: string
  registry-username:
    required: false
    type: string
  registry-password:
    required: false
    type: string

runs:
  using: composite
  steps:
  - name: Setup QEMU
    uses: docker/setup-qemu-action@v2
  - name: Setup Buildx
    uses: docker/setup-buildx-action@v2
  - name: Meta
    id: meta
    uses: docker/metadata-action@v4
    with:
      images: ${{ inputs.image }}
      tags: |
        type=sha,prefix=,suffix=-${{ github.run_attempt }}
        ${{ inputs.tags }}
      flavor: |
        latest=false
  - name: Login
    if: ${{ inputs.push == 'true' }}
    uses: docker/login-action@v2
    with:
      registry: ${{ inputs.image }}
      username: ${{ inputs.registry-username }}
      password: ${{ inputs.registry-password }}
  - name: Build${{ inputs.push && ' and push' || '' }}
    uses: docker/build-push-action@v4
    with:
      context: .
      pull: true
      push: ${{ inputs.push }}
      load: ${{ ! fromJSON(inputs.push) }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
      build-args: ${{ inputs.build-args }}
      labels: ${{ steps.meta.outputs.labels }}
      tags: ${{ steps.meta.outputs.tags }}

outputs:
  json:
    value: ${{ steps.meta.outputs.json }}
