ci:
  collect:
    numberOfRuns: 1
    startServerCommand: make serve/docker
    url:
    - http://localhost:8080/
  assert:
    # preset: lighthouse:all
    assertions:
      # csp-xss: off
      categories:performance:
      - warn
      - minScore: 1
      categories:accessibility:
      - error
      - minScore: 1
      categories:best-practices:
      - error
      - minScore: 1
      categories:seo:
      - error
      - minScore: 1
      categories:pwa:
      - warn
      - minScore: 1
