ci:
  collect:
    numberOfRuns: 3
    startServerCommand: make --assume-old=build/container serve/container
    startServerReadyPattern: serving initial configuration
    url:
    - http://localhost:8080/
  assert:
    assertions:
      categories:performance:
      - warn
      - minScore: 1
      categories:accessibility:
      - error
      - minScore: 1
      categories:best-practices:
      - error
      - minScore: 1
      categories:seo:
      - error
      - minScore: 1
