name: CI # TODO explore SARIF uploading and GH security

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - edited
    branches:
    - main

permissions:
  contents: read
  security-events: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Eject Makefile variables
      run: eval "$(make -q eject/github)"
    - name: EditorConfig
      uses: docker://docker.io/mstruebing/editorconfig-checker:2.4.0
    - name: Yamllint
      uses: docker://docker.io/pipelinecomponents/yamllint:0.25.0
      with:
        args: yamllint .
    - name: Build container image
      uses: ./.github/actions/container-image
      with:
        image: ${{ env.MAKEFILE_IMAGE }}
        tags: ci
        build-args:
          HUGO_RELEASE=${{ env.MAKEFILE_HUGO_RELEASE }}
    - name: Checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        config_file: checkov.yaml
    - name: Trivy
      uses: aquasecurity/trivy-action@0.10.0
      continue-on-error: true
      with:
        image-ref: ${{ env.MAKEFILE_IMAGE }}:ci
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: npm
    - name: Lighthouse
      run: |
        npm install -g @lhci/cli@0.12.0
        make test/lighthouse
