name: CI

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
    - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_wrapper: false
    - name: Setup node
      uses: actions/setup-node@v7
      with:
        node-version-file: .nvmrc
        cache: npm
    - name: Pull
      run: make -j pull/editorconfig pull/yamllint pull/checkov pull/trivy
    - name: Lint
      run: make lint
    - name: Build container image
      uses: ./.github/actions/container-image
      with:
        image: marshallford-me
        tags: ci
        build-args: HUGO_PARAMS_COMMIT=${{ github.sha }}
    - name: Scan
      run: make --assume-old=build/container scan
    - name: Test
      run: make --assume-old=build/container test
