name: Terraform

on: # yamllint disable-line rule:truthy
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions: {}

concurrency:
  group: terraform-${{ github.event_name == 'pull_request' && github.ref || 'apply' }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  image:
    name: Publish container image
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      id-token: write
      attestations: write
    env:
      IMAGE: us-central1-docker.pkg.dev/marshallford-marshallford-me/containers/marshallford-me
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Publish container image
      id: publish
      uses: ./.github/actions/container-image
      with:
        push: true
        image: ${{ env.IMAGE }}
        tags: |
          type=sha,prefix=,suffix=-${{ github.run_attempt }}
          type=raw,value=latest
        build-args: HUGO_PARAMS_COMMIT=${{ github.sha }}
        registry: us-central1-docker.pkg.dev
        registry-username: _json_key
        registry-password: ${{ secrets.GOOGLE_CREDENTIALS }}
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    needs:
    - image
    if: ${{ !cancelled() && contains(fromJSON('["skipped", "success"]'), needs.image.result) }}
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./terraform
    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      TF_CLI_ARGS_plan: ${{ github.event_name == 'pull_request' && '-lock=false' || '' }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} # TODO replace with Workload Identity Federation in new project/org
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Configure AWS credentials for terraform state
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::626319225102:role/pipeline-terraform-state
        aws-region: us-east-1
        aws-profile: terraform-state
    - name: Configure AWS credentials for marshallford.me
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::438616359965:role/pipeline-marshallford-me-iac
        aws-region: us-east-1
        aws-profile: marshallford-me
    - name: Read Terraform version
      id: terraform-version
      run: echo "version=$(< .terraform-version)" >> "$GITHUB_OUTPUT"
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: ${{ steps.terraform-version.outputs.version }}
        terraform_wrapper: false
    - name: Init
      run: terraform init
    - name: Validate
      run: terraform validate
    - name: Plan
      run: terraform plan -out="$RUNNER_TEMP/tfplan"
    - name: Apply
      if: github.event_name != 'pull_request'
      run: terraform apply "$RUNNER_TEMP/tfplan"
